BEGIN;

DROP TABLE tgl_nodes CASCADE;
DROP TABLE tgl_edges CASCADE;
DROP TABLE tgl_labels CASCADE;
DROP TABLE tgl_walks CASCADE;
DROP TABLE tgl_w2e CASCADE;
DROP TABLE tgl_l2n CASCADE;
DROP TABLE tgl_l2w CASCADE;

COMMIT;
