BEGIN;

DROP DOMAIN fk_id15;
DROP DOMAIN fk_id31;
DROP DOMAIN fk_id63;

DROP DOMAIN id15;
DROP DOMAIN id31;
DROP DOMAIN id63;

DROP DOMAIN bool_t;
DROP DOMAIN blittable;
DROP DOMAIN ch;
DROP DOMAIN str;
DROP DOMAIN ipv4;
DROP DOMAIN ipv6;

DROP DOMAIN i1;
DROP DOMAIN i2;
DROP DOMAIN i3;
DROP DOMAIN i4;
DROP DOMAIN i5;
DROP DOMAIN i6;
DROP DOMAIN i7;
DROP DOMAIN i8;
DROP DOMAIN i16;
DROP DOMAIN i24;
DROP DOMAIN i32;
DROP DOMAIN i64;
DROP DOMAIN u1;
DROP DOMAIN u2;
DROP DOMAIN u3;
DROP DOMAIN u4;
DROP DOMAIN u5;
DROP DOMAIN u6;
DROP DOMAIN u7;
DROP DOMAIN u8;
DROP DOMAIN u16;
DROP DOMAIN u24;
DROP DOMAIN u32;
DROP DOMAIN u63;

DROP DOMAIN direction;

DROP TYPE directions_enum;
DROP TYPE dtypes_enum;

COMMIT;