BEGIN;

DROP DOMAIN tgl_fk_id15;
DROP DOMAIN tgl_fk_id31;
DROP DOMAIN tgl_fk_id63;

DROP DOMAIN tgl_id15;
DROP DOMAIN tgl_id31;
DROP DOMAIN tgl_id63;

DROP DOMAIN tgl_bool;
DROP DOMAIN tgl_blittable;
DROP DOMAIN tgl_ch;
DROP DOMAIN tgl_ne_str;
DROP DOMAIN tgl_ipv4;
DROP DOMAIN tgl_ipv6;

DROP DOMAIN tgl_i1;
DROP DOMAIN tgl_i2;
DROP DOMAIN tgl_i3;
DROP DOMAIN tgl_i4;
DROP DOMAIN tgl_i5;
DROP DOMAIN tgl_i6;
DROP DOMAIN tgl_i7;
DROP DOMAIN tgl_i8;

DROP DOMAIN tgl_i16;
DROP DOMAIN tgl_i24;
DROP DOMAIN tgl_i32;
DROP DOMAIN tgl_i64;

DROP DOMAIN tgl_u1;
DROP DOMAIN tgl_u2;
DROP DOMAIN tgl_u3;
DROP DOMAIN tgl_u4;
DROP DOMAIN tgl_u5;
DROP DOMAIN tgl_u6;
DROP DOMAIN tgl_u7;
DROP DOMAIN tgl_u8;

DROP DOMAIN tgl_u16;
DROP DOMAIN tgl_u24;
DROP DOMAIN tgl_u32;
DROP DOMAIN tgl_u63;

DROP DOMAIN tgl_direction;

DROP TYPE tgl_directions_enum;

COMMIT;